### ISSUE TITLE
restarting jack in qjacktl does not reflect in jack-select

### ISSUE THREAD

**Issue by revast** [SpotlightKid/jack-select#3] opened 2018-09-07 11:20 UTC
hi, I think I found a bug:

When I start JACK via Qjackctl, jack-select goes green. When I stop it in Qjackctl, it gets red. But when I now start it again in Qjackctl, it stays red, the stop jack is grayed out. I did not see this with cadence, where it gets green when I start the first time, and when I stop and start again, it also works as it should - IF  I quit jack-select, and start it new. If I leave it open, then start JACK via cadence, it shows the same erroneous behaviour: it stays red

**Comment by SpotlightKid** [comment] 2018-09-07 13:28
I can't reproduce this. Are you sure you are starting JACK via DBUS in both instances from QjackCtl/Cadence?

`jack-select` only listens to the DBUS notifications about the JACK status, it doesn't work with JACK started as a normal (background) program without DBUS support.

Check which versions of JACK are running with `ps -x | grep jack`. There should be only `jackdbus`, not `jackd`.

**Comment by SpotlightKid** [comment] 2018-09-16 19:01
Closing this, since there was no further feedback. If the problem persists, feel free to re-open the issue.

**Closed as completed by SpotlightKid** 2018-09-16 19:01 UTC
Labels: needs feedback
